coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 0.1%
    patch:
      default:
        target: 90%
        threshold: 0%
        only_pulls: true
        paths:
          - "crates"
